### ISSUE TITLE
Base case for super simpletons?

### ISSUE THREAD

**Issue by Ypot** [meedstrom/org-node#1]
Hi! 

A super links user here for Zettelkasten. 

A little bit overwhelming the instructions for the org roam users. Could you advice me a very simple example to start with??

Thanks for your package, since it seems to be 100% compatible with vanilla emacs, it could be the first package of its kind I try. 

Best regards.

**Comment by meedstrom** [comment]
Hi, thanks for reaching out! Is it better now? What sort of examples would
you want to see?

**Comment by meedstrom** [comment]
I've added a quick-start section. In retrospect, that's obviously a good idea. Thanks for suggesting it!

**Comment by Ypot** [comment]
Thanks for the quick start!

But it works a little bit weird. I do: find-node and it jumps to a node not related with the search results.

Maybe I have installed it wrong?

1. I downloaded the org-node-master
2. I added it to the load path
3. I added to the init: 
    (require 'org-node)
   (add-hook 'org-mode-hook 'org-node-cache-mode)
4. Done

**Comment by meedstrom** [comment]
Thanks for explaining how you install it. I'll actually test it that way too.

A question: do you jump to the wrong file, or just to the wrong position in the correct file?

**Comment by meedstrom** [comment]
OK, the latest commit may have fixed it?  

I found that in buffers with Unicode (non-ASCII) letters, it was jumping to the wrong position - more unicode, more wrong.   

Now `org-node-reset` will be maybe 25% slower but that's the price of correctness, heh.  BTW, does `org-node-reset` take many seconds for you? I filed issue #2 after trying it on a fresh install.

**Comment by Ypot** [comment]
> OK, the latest commit may have fixed it?

Fixed!
> 
> I found that in buffers with Unicode (non-ASCII) letters, it was jumping to the wrong position - more unicode, more wrong.
> 
> Now `org-node-reset` will be maybe 25% slower but that's the price of correctness, heh. BTW, does `org-node-reset` take many seconds for you? I filed issue #2 after trying it on a fresh install.

19.5 seconds
org-node: found 4 files, 12371 subtrees and 1255 links in 19.50s

To advance from the quick start: now I know how to create a link, and how to find headlines with links (or IDs) in them. What would be the next step?

**Comment by meedstrom** [comment]
Thanks! That's a massive performance bug... I gotta fix that.

Ah, the next step... if you want to try out the idea of zettelkasten, atomic notes, this is the magical and probably uncomfortable moment. The next time you want to create yet another subtree, consider doing this instead:

1. Keep in mind which heading you might have created this under
2. Run `org-node-find` and type out the new node name.  
   - Yes, the name of a node that doesn't exist.  The exact name you choose now is not so important since you can rename it later.
   - This will create a new file-level node.
4. Having created this new node, you can then use `org-node-insert-link` to link to that heading you remembered in step 1.  That way there's still a way to find the connection :)

With that said, it is not mandatory to create file-level nodes, if you want to keep doing it using subtrees you can configure `org-capture` -- there's a section on the README about it :)  But I'd advise trying it with file-level nodes for a while anyway.  I've got 2000 files, a few of them are very big trees with lots of headings, but most are tiny atomic notes with no headings or just 1-2 headings.

**Comment by Ypot** [comment]
> Thanks! That's a massive performance bug... I gotta fix that.
> 
> Ah, the next step... if you want to try out the idea of zettelkasten, atomic notes, this is the magical and probably uncomfortable moment. The next time you want to create yet another subtree, consider doing this instead:
> 
>     1. Keep in mind where you might have created this subtree, what topic it was
> 
>     2. Run `org-node-find` and type out the new node name.
>        
>        * Yes, the name of a node that doesn't exist.  The exact name you choose now is not so important since you can rename it later.
>        * This will create a new file-level node.
> 
>     3. Having created this new node, you can then use `org-node-insert-link` to link to some of the related nodes you remembered in step 1.  That way there's still a connection :)
> 

It works, but not my way of using Zettelkasten...

> With that said, it is not mandatory to create file-level nodes, if you want to keep doing it using subtrees you can configure `org-capture` -- there's a section on the README about it :) But I'd advise trying it with file-level nodes for a while anyway.
> 
> I've got 2000 files, a few of them are very big trees with lots of headings, but most are tiny atomic notes with no headings or just 1-2 headings. They're published on https://edstrom.dev/all

I get the use of org-node for searching nodes, but I don't see it clearly to generate new nodes. I will keep trying.

**Comment by meedstrom** [comment]
Oh yea, I wonder how to write a capture template that visits a subtree node and creates a child subtree there with a new ID...  But you can always just jump to that heading and use `org-node-insert-heading-node` (btw, that's the renamed command you mentioned earlier).
