### ISSUE TITLE
org-node 0.3 chews through battery in Termux (timer issue?)

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#21]
So I run Emacs in Termux on Android so I have access to all of my org-roam notes, and the native org-roam operations for some reason end up very costly in this environment, and I was very happy to find quickroam and then org-node to resolve this.

I have to run Termux in non-battery optimising unrestricted mode, otherwise Android ends up killing it and I have to restart Emacs and that takes a bit and defeats the purpose of having access to being able to quickly make notes. This is usually fine and battery monitor reports say that Termux uses something like 0.1% of battery in the background. But with the org-node 0.3 update, this jumped to Termux using over 50% of the battery in the background.

I think the issue is the timers, which end up keeping waking up Termux and so using battery. Is there a good way of turning off the timers?  (& maybe just checking on saves?)

**Comment by meedstrom** [comment]
Yea I see! Should be possible to test if that’s the problem by doing

(fset 'org-node--schedule-idle-reset 'ignore)

But it would be surprising, since these are idle timers, which do not
repeat forever. Ie if you’ve been idle for 60 seconds and that triggers a
60s idle timer, it’s not gonna trigger again at 120 seconds in. Only after
the idleness state is zeroed can it trigger again.

Anyway it is indeed not that important to run the timer. The tables should
stay up to date if my mental model is correct… but that sort of thing is
hard to guarantee :) But they won’t pick up stuff synced from other devices
without a M-x org-node-reset!

**Comment by meedstrom** [comment]
Ok I just realized something. It might be repeating forever after the first
timer triggers. So thats why my laptop got warm?! Bloody Emacs timer
footguns…

**Comment by emacsomancer** [comment]
Ah! I'm pretty sure something like that must be the case, because everything was fine for my phone one day and then it chewed through battery like anything the next and I was disabling a bunch of things and nothing helped and then I tried a battery monitor and found it was Termux, and tried just running Termux without Emacs and that was fine, so tried to think what would have changed. And rolling back org-node to 0.1pre seemed to fix it.

**Comment by meedstrom** [comment]
Thanks very much for the report :) I’ll fix tomorrow.

**Comment by meedstrom** [comment]
It’s quite strange that code. I don’t know if you noticed, but it doesn’t
actually do anything, just starts more timers.  I must have been tired.

**Comment by emacsomancer** [comment]
Ah - I hadn't noticed at first that `org-node--schedule-idle-reset` just calls itself. (Easy to miss at first.)

Presumably this being changed to actually performing the reset will fix the Termux issue since it won't continually wake it up. (Still, perhaps at some point the idle time lapse could be exposed to user customisation.)

**Comment by meedstrom** [comment]
I don't think you'll have the issue anymore. But if so,

    (fset #'org-node--maybe-adjust-idle-timer #'ignore)
