### ISSUE TITLE
[FR] TODO STATES

### ISSUE THREAD

**Issue by Ypot** [meedstrom/org-node#3]
When inserting links, I think it shouldn't add the TODO STATE to the link description.

**Comment by meedstrom** [comment]
Agreed.  I assume you are using file-local `#+todo:` settings?

I've had an idea knocking around for a way to handle that.  Newest master has an attempted fix!

**Comment by Ypot** [comment]
> Agreed. I assume you are using file-local `#+todo:` settings?
> 

Nope. In my init file, example:
 '(org-todo-keywords
   '((sequence "PROJ(P)"  "|" "CANCELED(c@)")))

> I've had an idea knocking around for a way to handle that. Newest master has an attempted fix!

Not working, I think.

**Comment by meedstrom** [comment]
Hmm. What does `(org-node-cache--make-todo-regexp)` return for you?

**Comment by meedstrom** [comment]
Updated syntax since I asked that.

Given your org-todo-keywords, the code uses this expression

    (org-node-worker--make-todo-regexp
      (string-join (mapcan #'cdr '((sequence "PROJ(P)" "|" "CANCELED(c@)")))
                   " "))

which is the same as this

    (org-node-worker--make-todo-regexp "PROJ(P) | CANCELED(c@)")

which returns the regexp

    "\\(?:CANCELED\\|PROJ\\)"

which should match your todo states if they are only CANCELED or PROJ.  

So -- ohhhh wait.  Do you have any text before the state? I think that's not Org syntax but I'm learning every day heh.
