### ISSUE TITLE
Feature Request: Link removal with proper backlinks update

### ISSUE THREAD

**Issue by hpgisler** [meedstrom/org-node#50]
Is there a command to remove a link inside heading A which points to a heading B, which also auto updates B's `:BACKLINKS:` property by removing heading A from it?

Or is it intended procedure to call `org-node-backlink-fix-all` or `org-node-backlink-fix-whole-buffer` respectively in such situations?

**Comment by meedstrom** [comment]
No command, but `org-node-backlink-mode` will update heading B the next time you edit some text at or under heading B and save.

Hm. Maybe that could be improved.

**Comment by hpgisler** [comment]
Ah, I see..
I was not aware of this trigger behavior.

(I expected somehow, that a removal of the link under heading A would somhow trigger auto-update on all `:BACKLINKS:` to it.. )

**Comment by meedstrom** [comment]
Now I have an idea for an option that, if enabled, would do that auto-update. If I'm thinking about it correctly, much of the logic is already there where `org-node-perf-eagerly-update-link-tables` is consulted.

I'll probably try it later tonight.

**Comment by meedstrom** [comment]
Interesting challenge, since I have an extreme case of a file that contains ~3000 links.

Tried a naive design where on save, all links previously known to exist in the file are added to some list X, then the tables are updated (possibly with additions or deletions compared to X... call the new link set Y), then all targets of X are visited to maybe fix the backlinks. Visiting up to 3000 unique files can take a while :)  Anyway, now it will diff X-Y and only visit where changes are needed. That seems to be fast on my device.

Enable via setting option `org-node-backlink-aggressive` to t.  Thinking about merging this option with `org-node-perf-eagerly-update-link-tables`.

Also turned org-node-backlink-mode into a global mode.

**Comment by hpgisler** [comment]
Great!

I tested it and it works :+1: 
I noted 2 things:

1. if I do `org-store-link` in B.org (original file, w/o any modifications to be saved) and then do an `org-insert-link` in A.org, link in A.org and back-link in B.org are created (without first saving A.org - which is cool..), but B.org is not saved automatically. On the other hand (after saving both files) if I then remove the link in A.org and then save A.org, the back-link is removed from B.org, and B.org is saved automatically. I.e. the behavior for auto-saving B.org is not symmetric on insertion vs. removal of the backlink. (note. If I close B.org before inserting the link in A.org, the backlink gets added - as expected - in B.org, without an open buffer of B.org after that op.)
2. in `defcustom org-node-perf-eagerly-update-link-tables t` it is stated:
```
An user of `org-node-backlink-mode' is recommended to enable this as
well as `org-node-backlink-clean-aggressively'."
```
however, I think it should read:
```
An user of `org-node-backlink-mode' is recommended to enable this as
well as `org-node-backlink-aggressive'."
```
right?

**Comment by meedstrom** [comment]
1. Hm. There is a kind of symmetry, the idea is it will leave B.org unsaved if it has previously been modified and was not yet saved, since I don't want to force the user to save what they may not intend to save. However, if B.org is unmodified, then it will save.  Basically: unmodified -> unmodified and modified -> modified.
2. Whoops, yea.

**Comment by meedstrom** [comment]
You're right, it is not *quite* symmetric.

**Comment by hpgisler** [comment]
> 1. Hm. There is a kind of symmetry, the idea is it will leave B.org unsaved if it has previously been modified and was not yet saved, since I don't want to force the user to save what they may not intend to save. 

Totalli agree.

> However, if B.org is unmodified, then it will save. 

which is not currently the case, right?

**Comment by hpgisler** [comment]
Thanks big time - by the way - for your help and time!

**Comment by meedstrom** [comment]
Fixed, I believe. Thanks too.
