### ISSUE TITLE
dash dependency?

### ISSUE THREAD

**Issue by bdarcus** [meedstrom/org-node#9]
Minor thing, but do you really need the `dash` dependency?

From a quick look, it seems to be used in a couple/few places, and that the built-in `seq-map` and such could allow you to eliminate a dependency.

**Comment by meedstrom** [comment]
Out of curiosity, how would you feel if I depend on [Llama](https://git.sr.ht/~tarsius/llama) instead of Dash? Maybe that one has a better shot at being integrated into Emacs core.

**Comment by bdarcus** [comment]
IDK; had never heard of it.

I was just asking because at least some of the dash functions you use (union, map, etc) have built-in equivalents.

**Comment by meedstrom** [comment]
Mmm... there are built-in equivalents to `-map`, but not to `--map`.

And `-union` or `-uniq`, I'll give you that `seq-union` and `seq-uniq` exist, but I do not depend on seq.el at all since I am anyway depending on dash.el :) A codebase should pick a minimum vocabulary, basically "pick one library and stick with it", I think.

**Comment by bdarcus** [comment]
Sure; it's your choice of course.

Was just wondering.

**Comment by meedstrom** [comment]
I'll keep this open. Want to see how much people care about this.

**Comment by meedstrom** [comment]
Alright, after discussion on https://old.reddit.com/r/emacs/comments/1cncbe2/do_you_react_when_a_package_depends_on_dash_why/l3badyz/?context=3, I arrived at some lessons:

1. In Emacs Lisp, lambdas are just slow, so seq and many cl-* functions are never gonna be fast when you pass a lambda - only when you pass a function created by defun.  For example, `(seq-map #'cl-evenp '(1 3 5 6))` is fine, but `(seq-map (lambda (num) (cl-evenp num)) '(1 3 5 6))` is slow.
2. Dash's anaphoric macros (like `--map`) often *look* like they're implicitly creating a lambda for you, but they're actually just doing a while-loop internally.
3. Performance-wise, whenever you want to iterate, the best options come from this set
   * `cl-loop` (it's the fastest possible elisp when the list length is fixed and known)
   * A regular `while` loop
   * A dash macro, because it just expands to a `while` loop

Most of the places where I now use a dash macro, the equivalent in `cl-loop` or `while` would span multiple lines.  Not a big deal per se, but I am skeptical whether rephrasing all dash invocations as cl-loop invocations really helps readability, for a newcomer unfamiliar with both.

A drawback with Dash is you don't get to name the arguments, instead it always names them "it" and "other".  Argument-naming is a nice documentation technique.  

A drawback with cl-loop is unreadable backtraces.

In the future, it might be nice to see Emacs have new set of looping utilities, that don't do dash's weirdness with the anaphoric arguments, but that still let you pretend you're passing lambdas. Maybe based on exposing [transducers](https://git.sr.ht/~fosskers/transducers.el) in an extra-performant way, manufacturing cl-loop invocations for you with a dash-like UI that lets you name the arguments? One can dream.

**Comment by meedstrom** [comment]
You know, I think you've given me a new package idea.

**Comment by meedstrom** [comment]
After 4 months, I should correct myself.

> In Emacs Lisp, lambdas are just slow

In interpreted code yes, in compiled code no.  It seems Elisp will compile all the lambdas in a file, at least if they are not quoted like `'(lambda ...)`.  And then the benchmarks I tried look fine.

In highly performance-critical code, it can be still faster to hand-write something using `while`, which is what cl-loop and Dash do for you.  

NB: Some functions in Dash that are super performant.  `-union` is 10x faster than `seq-union`!  I believe `-difference` and `-intersection` also crush their competitors.

### Dash dropped

I have been able to drop Dash now because

1. I understand enough elisp to do an equivalent to `-union` performantly
2. I like the aesthetics of cl-loop, and many situations are solvable with it
3. Compiled lambdas perform OK, as mentioned above
